### ISSUE TITLE
missing pipelining capabilities

### ISSUE THREAD

**Issue by rikatz** [criteo/haproxy-spoe-go#11]
Hello,

I've been using the library, but got the following error:

```
time="2020-11-23T17:53:16-03:00" level=debug msg="spoe: hello from 127.0.0.1:53794: map[capabilities: healthcheck:true max-frame-size:16380 supported-versions:2.0]" func="github.com/criteo/haproxy-spoe-go.(*conn).handleHello" file="/home/rkatz/go/pkg/mod/github.com/criteo/haproxy-spoe-go@v1.0.1/hello.go:30"
```

I'm using HAProxy 2.3, but it fails also with 2.4.

The following is the config I've been using, but apparently even forcing the pipelining capabilities (or trying to change the max-frame-size to make some tests) it doesn't seems to reflect in the hello packet:

```
[modsecurity]
spoe-agent modsecurity-agent
    max-frame-size 1024
    messages modsecurity
    option var-prefix modsec
    timeout hello 10s
    timeout idle  2m
    timeout processing 1000ms
    use-backend spoe-modsecurity
    log global

spoe-message modsecurity
    args method=method path=path query=query reqver=req.ver ip=src reqhdrs=req.hdrs_bin reqbody=req.body ignorerules=var(txn.ignorerules) srvip=dst srvport=dst_port
    event on-frontend-http-request
```

Thanks

**Comment by rikatz** [comment]
Aparently disabling the spop-check option it works fine.

I'll leave this open to check if this is the desired behavior or if something needs to be reviewed :)

Thanks!

**Comment by ShimmerGlass** [comment]
Hello, this is not an error, this is a debug log indicating a new connection from haproxy to your spoe module.

**Comment by ShimmerGlass** [comment]
I'm closing this, please reopen if something's unclear.

**Comment by rikatz** [comment]
Will take a look again, thanks
