### ISSUE TITLE
panic: sync: negative WaitGroup counter

### ISSUE THREAD

**Issue by rikatz** [criteo/haproxy-spoe-go#13]
Hello,

While doing some stress tests here, we've found the following error:

`panic: sync: negative WaitGroup counter`

Here's the stack trace:
```
panic: sync: negative WaitGroup counter

goroutine 2650 [running]:
sync.(*WaitGroup).Add(0xc001822f80, 0xffffffffffffffff)
        /usr/local/go/src/sync/waitgroup.go:74 +0x147
sync.(*WaitGroup).Done(0xc001822f80)
        /usr/local/go/src/sync/waitgroup.go:99 +0x34
github.com/criteo/haproxy-spoe-go.(*conn).run(0xc00188b220, 0xc00002a600, 0x0, 0x0)
        /go/pkg/mod/github.com/criteo/haproxy-spoe-go@v1.0.1/conn.go:131 +0xa00
github.com/criteo/haproxy-spoe-go.(*Agent).Serve.func1(0x97c100, 0xc00019c8b8, 0xc00002a600)
        /go/pkg/mod/github.com/criteo/haproxy-spoe-go@v1.0.1/spoe.go:100 +0xcc
created by github.com/criteo/haproxy-spoe-go.(*Agent).Serve
        /go/pkg/mod/github.com/criteo/haproxy-spoe-go@v1.0.1/spoe.go:93 +0x167
```

Thanks :D

**Comment by rikatz** [comment]
Another thing for now I'm thinking is about proposing to use netutil.LimitListener to see how it behaves :)

**Comment by cpaillet** [comment]
Hi,

Can you try again with the bug fix I provide a few minutes ago ?

thanks

cedric

**Comment by rikatz** [comment]
Sure! I'm running some mocked tests right now, will do ASAP!

Thank you!

**Comment by rikatz** [comment]
@cpaillet it seems the negative wg is solved. 

We're doing some perf tests here and facing some other locks and some strange behaviors, like a lot of broken pipes.

I'll make some more tests in a local env to see if the behavior keeps, but for now I think this issue can be closed.

Thank you very much for the correction and your time!

**Comment by cpaillet** [comment]
Hi,

Thanks for you answer.
We will continue to improve the code quickly, This fix reduce the performances.
