### ISSUE TITLE
Can I use the SID from haproxy

### ISSUE THREAD

**Issue by git001** [criteo/haproxy-spoe-go#28]
I use this great module, thanks for writing.
Can I use the stream id from the event?

```
SPOE: [agent-on-http-req] <EVENT:on-frontend-http-request> sid=88 st=0 0/0/0/0/0 1/1 0/0 10/33
00000058:streams.srvrep[0028:002a]: HTTP/1.0 200 
00000058:streams.srvhdr[0028:002a]: content-type: text/plain
00000058:streams.srvcls[0028:002a]
SPOE: [agent-on-http-res] <EVENT:on-http-response> sid=88 st=0 0/0/0/0/0 1/1 0/0 10/33
```

**Comment by ShimmerGlass** [comment]
Hello @git001, today the stream id is not exposed to the library clients. May I ask what is your use case with this ?

**Comment by git001** [comment]
I have to count how many clients are connected to a specific URL, because of that the Stream ID would help to correlate events.

**Comment by ShimmerGlass** [comment]
I dont think this would work : 
* A client may open several tcp connections to load a web page (see: https://docs.pushtechnology.com/cloud/latest/manual/html/designguide/solution/support/connection_limitations.html)
* I not sure the stream id would work well to correlate to the number of connections when using multiple haproxy thread/processes (each could maintain their own counter), or at least I saw no guarantee in the documentation about that.

If you are interested in the number of tcp connections, I suggest you try using the `on-frontend-tcp-request` SPOE event.

If you want to count the number of actual clients, you can either set a unique cookie per client (and then get it back in SPOE by reading the request headers if you want), or provide per-client API keys, depending on your use case.

**Comment by git001** [comment]
Well you are right about the `on-frontend-tcp-request` but I need the URL, that's the reason why I choose `on-frontend-http-request`.

We also want to know how many streams a client creates per URL.

The problem with the cookie that this is a setup where you have no cookies just some streaming URLs.
I don't know how the [hls.min.js](https://cdn.jsdelivr.net/hls.js/latest/hls.min.js) behave when I add some cookies.

Here the spoe config.
```
[agent-on-http-req]
spoe-agent agent-on-http-req

    log global

    messages agent-on-http-req

    option var-prefix feevents

    timeout hello      2s
    timeout idle       2m
    timeout processing 1s

    use-backend agent-on-http-req

spoe-message agent-on-http-req
    args my_path=path my_src=src
    event on-frontend-http-request
```

**Comment by git001** [comment]
Well it looks like that the streamID is there https://github.com/criteo/haproxy-spoe-go/blob/master/frame.go#L46 ;-) 
How about to add a capital S to tell go to make it available in Frame struct?

**Comment by ShimmerGlass** [comment]
Yes, it is technically possible to make it available, tho not through the frame object because it is not exposed to the users (your PR would need to be reworked).
However, as I explained above, AFAIK it doesn't do what you think it does, and I don't see how users could use it in a meaningful way.
Adding more fields / methods makes the API more complex for users to understand, could be misleading, and adds backward compatibility constraints. 

Given those points I won't expose this field unless additional arguments are presented.

**Comment by git001** [comment]
> Yes, it is technically possible to make it available, tho not through the frame object because it is not exposed to the users (your PR would need to be reworked).

I recognized it after created the PR. Feel free to delete or ignore the PR.

I assume that the Stream ID is showing how many concurrent streams are created from a client. I don't think that this can be done with cookies, but I'm ready to learn.

Do you know that every stream have there own cookie, I don't think so.

**Comment by mougams** [comment]
As mentioned in https://github.com/criteo/haproxy-spoe-go/issues/40#issuecomment-1795136138, we're dropping support on the project, and archiving it.
