### ISSUE TITLE
Incompatibility with HAProxy's nbthread > 1

### ISSUE THREAD

**Issue by bedis** [criteo/haproxy-spoe-go#3]
When HAProxy is running 1 process and 1 thread, everything works smoothly.
If running multiple processes (nbproc > 1), this would still works smoothly.
That said when I enabled multiple processes, HAProxy does not announce async mode and haproxy-spoe-go lib simply refuses the connection:
```
INFO[3397] spoe: hello from 127.0.0.1:41537: map[capabilities:pipelining engine-id:6A27BD77-B2EC-475F-B258-E59B68CC3E4E max-frame-size:16380 supported-versions:2.0] 
ERRO[3397] spoe: error handling connection: hello: expected capabilities [async pipelining] 
```

Would be great if the library can adapt itself to the capabilities announced by HAProxy

**Comment by ShimmerGlass** [comment]
Resolved in master !

**Comment by bedis** [comment]
Brilliant, thx!
Will give it a try asap

**Comment by bedis** [comment]
I confirm it works for me :)
