### ISSUE TITLE
When SPOE handler returns an error, haproxy-spoe-go does not return anything to HAProxy and the request makes progress in HAProxy only when we hit the timeout for HAProxy <--> SPOA.

### ISSUE THREAD

**Issue by 15ljindal** [criteo/haproxy-spoe-go#38]
### SETUP

Here is what I have put in hapoxy.config:
```
# register spoa
filter spoe engine myspoa config .../myspoa.conf

http-request send-spoe-group myspoa module1
```

Here is myspoa.conf:
```
[myspoa]
spoe-agent myspoa
    groups module1
    timeout hello 2s
    timeout idle  2m
    timeout processing 10s # ***** CRUCIAL FOR THIS ISSUE
    use-backend agents
    log global

spoe-group module1
    messages module1

spoe-message module1
```

In my main.go:
```
func main() {
	log.Println("Hello from SPOA!")
	logurs.SetLevel(logurs.DebugLevel) // enabled debug log in SPOE library

	// TODO: can specify a custom config for the SPOA e.g. update max connections
	agent := spoe.New(customSpoeHandler)

	if err := agent.ListenAndServe(":12345"); err != nil {
		log.Fatal(err)
	}
}
```

Let's say in some situations `customSpoeHandler` returns `nil, fmt.Errorf("Some error message")`. This could be due to any reason, e.g. a message which we do not want to handle.

### What I expect?
SPOA will still return something to HAPRoxy **immediately** so that the request can make progress in HAProxy.

### What happens?
When I send a request using curl, the response comes back after 10 seconds, the timeout configured for HAProxy-SPOA communication.

### Possible issue
Most likely due to an unhandled condition here - https://github.com/criteo/haproxy-spoe-go/blob/master/notify.go#L111
```
	actions, err := c.handler(messages)
	if err != nil {
		return errors.Wrap(err, "handle notify") // TODO return proper response
	}
```

### Workaround
The workaround seems to be that `customSpoeHandler` should always return `nil` in the `error` field. It seems fine to return `nil` spoe action.

**Comment by mougams** [comment]
As mentioned in https://github.com/criteo/haproxy-spoe-go/issues/40#issuecomment-1795136138, we're dropping support on the project, and archiving it.
