### ISSUE TITLE
Memory/Goroutine leak

### ISSUE THREAD

**Issue by 15ljindal** [criteo/haproxy-spoe-go#39]
# Summary
When HAProxy sends diconnect frame with specific "status codes" (e.g. [I/O error](https://github.com/criteo/haproxy-spoe-go/blob/master/errors.go#L25)), we leak goroutines. This leads to memory leak. Eventually, the process dies to OOM.

In our test environment, we observed that if there is a high rate of such disconnect frames sent by HAPRoxy, the memory consumption can reach upto 120G in less than 10 minutes. Note: We were sending several KBs of data in each haproxy --> SPOA call; at 100k requests/second.

# Details
Here is my analysis. All the details below may not be correct - but overall it does look like there is a leak in "haproxy-spoe-go".

All the goroutines seem to be stuck here - https://github.com/criteo/haproxy-spoe-go/blob/v1.0.6/notify.go#L130

Here is the reason for goroutine leak:

This is the "main run loop": https://github.com/criteo/haproxy-spoe-go/blob/v1.0.6/conn.go#L26

There are two main loops (conceptually):

1. "response loop" to send the response back to haproxy from SPOA. This is done as part of a gouroutine here - https://github.com/criteo/haproxy-spoe-go/blob/v1.0.6/conn.go#L106. Two things to note here:
    - This go routine will read data from channel "frames" and send data to haproxy.
    - This goroutine will exit when there is an event on channel "done". Once it exits, there is no one to read from channel "frames". Hence, any writes on channel "frames" will block.

2. "request loop" to read data sent by haproxy and act on it. This is not a separate go routine, rather part of the "main run loop" here - https://github.com/criteo/haproxy-spoe-go/blob/v1.0.6/conn.go#L122
 
Here is what happens.

1. Due to short processing timeout of 10ms on haproxy side for SPOA calls, there are a lot of disconnects sent by haproxy to SPOA.
2. When SPOA rcvs a disconnect frame from haproxy, it calls method "handleDisconnect" here - https://github.com/criteo/haproxy-spoe-go/blob/v1.0.6/conn.go#L140. "handleDisconnect" returns a non-nil error, because the "status-code" is set to "I/O error" in the disconnect frame sent by haproxy to SPOA - https://github.com/criteo/haproxy-spoe-go/blob/v1.0.6/disconnect.go#L64. (We can look at haproxy code to understand when haproxy sets this status code.).
3. As can be seen here - https://github.com/criteo/haproxy-spoe-go/blob/v1.0.6/conn.go#L142 - on a non-nil error while handling disconnect, the "main run loop" will return.
4. When the "main run loop" returns, channel "done" is closed - https://github.com/criteo/haproxy-spoe-go/blob/v1.0.6/conn.go#L29
5. When channel "done" is closed, the "response loop" goroutine will exit.
6. Since there is no one to read from "frames" channel, all the gouroutines launched as part of "runWorker" here - https://github.com/criteo/haproxy-spoe-go/blob/v1.0.6/conn.go#L136 - will be blocked on the frames channel... INDEFINITELY
7. AND WE HAVE A GOROTUINE LEAK... hence a memory leak.

# Misc
Memory leak
![memory_leak](https://github.com/criteo/haproxy-spoe-go/assets/60752662/5c3c420f-2b61-4629-944a-b9e99cd8ddda)

Error message from logs
![error_msg](https://github.com/criteo/haproxy-spoe-go/assets/60752662/fe0e89ab-b80d-474d-9b82-5968e10fdeac)

Go routine leak
![goleak_1](https://github.com/criteo/haproxy-spoe-go/assets/60752662/85a5415b-bfcc-491c-a429-b65b25273f12)

![goleak_2](https://github.com/criteo/haproxy-spoe-go/assets/60752662/2e95de30-56df-4067-aa3c-b95dc106d0ba)

Attached are some snapshots of the logs messages from our golang process and pprof profiles.

**Comment by 15ljindal** [comment]
Someone else also ran into the exact same issue - https://github.com/negasus/haproxy-spoe-go/issues/18#issuecomment-1755719465

**Comment by mougams** [comment]
As mentioned in https://github.com/criteo/haproxy-spoe-go/issues/40#issuecomment-1795136138, we're dropping support on the project, and archiving it.
