### ISSUE TITLE
When is the new release?

### ISSUE THREAD

**Issue by 15ljindal** [criteo/haproxy-spoe-go#40]
Last release 1.0.6 was in Jan 2021. I see that there have been several commits since then. These unreleased commits fix some critical issues e.g. memory corruption fix in https://github.com/criteo/haproxy-spoe-go/commit/003022c63572cec6b9f68f6d3dd2bcc8121c82dc

Can you please release a new version of this framework?

**Comment by mougams** [comment]
Hi @15ljindal  - thank you for your interest on this project.

We're planning to drop support on this project, and will soon put it into maintenance.
I'd advise you to instead use and migrate to the other project https://github.com/negasus/haproxy-spoe-go, which is pretty well active and maintained.

**Comment by 15ljindal** [comment]
Thank you @mougams 
Can you do one final release for this project? That will allow us to get the known issues fixed asap.

And then we can plan the migration to the other project.

**Comment by mougams** [comment]
I've released v1.0.7 https://github.com/criteo/haproxy-spoe-go/releases/tag/v1.0.7. Enjoy!

**Comment by mougams** [comment]
Released
