### ISSUE TITLE
question: decoding headers

### ISSUE THREAD

**Issue by mroach** [criteo/haproxy-spoe-go#5]
I'm very new to both Go and HAProxy, but I've got a good working prototype going using your code; thanks!

The last issue I have is how to decode headers. I'm sending the headers from HAproxy using [req.hdrs_bin]. I've dumped the data and did a little decoding (in Elixir; but it works). I confirmed the format: an integer indicating the length of bytes to come, the bytes, and the EOF marker is double `NUL` chars.

```
[
  <<4>>, "h", "o", "s", "t",
  <<14>>, "l", "o", "c", "a", "l", "h", "o", "s", "t", ":", "8", "0", "5", "5"
  <<10>>, "u", "s", "e", "r", "-", "a", "g", "e", "n", "t",
  <<11>>, "c", "u", "r", "l", "/", "7", ".", "5", "4", ".", "0",
  <<6>>, "a", "c", "c", "e", "p", "t",
  <<16>>, "a", "p", "p", "l", "i", "c", "a", "t", "i", "o", "n", "/", "j", "s", "o", "n",
  <<0>>, <<0>>
]
```

I'm searching through the code seeing if there's a decoder for this built in. I found [decodeKVs] but that's not exported and reading it, I don't think it would decode this.

Have you solved the header problem? If you could provide a code snippet to do so, that would be great. I would be happy to open a PR to update the README to include that.

### Edit

I've used my 1 day old Go skills to come up with this

```go
// Parses the HAProxy binary format into a list of strings. The byte format is:
//   <chunk size><chunk> ... \0 \0
// For example the string "host" would be encoded as:
//   []byte{4 ,104 ,111 ,115 ,116, 0, 0}
// 4 is the length of the string, then the four bytes. more chunks could follow
// the end of message indicator is the double NIL chars
func decodeStrings(bytes []byte) []string {
	var res []string
	offset := 0

	for offset < len(bytes) {
		size := int(bytes[offset])
		offset += 1

		if size > 0 {
			str := string(bytes[offset : offset+size])
			res = append(res, str)
		}

		offset += size
	}

	return res
}

func decodeHeaders(bytes []byte) map[string]string {
	res := make(map[string]string)
	strings := decodeStrings(bytes)
	offset := 0

	for offset < len(strings) {
		key := strings[offset]
		value := strings[offset+1]
		res[key] = value
		offset += 2
	}

	return res
}
```
[req.hdrs_bin]: https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#7.3.5-req.hdrs_bin
[decodeKVs]: https://github.com/criteo/haproxy-spoe-go/blob/97891c13d324d1a01ea960648696bd1128162adf/encoding.go#L176

**Comment by ShimmerGlass** [comment]
Hi, thanks for you feedback !
This use case is not handled by the library yet. Your function is a great start, here are some comments : 
* According to the doc, the length of each string is encoded using `varint` and not a single byte. This means you can use the `decodeString()` function read the strings : 
``` 
i:= 0
for i < len(bytes) - 2 { // ignore the two last NULL bytes
   s, n, err := decodeString(bytes[i:])
   // handle error
   i += n
   // handle string
}
```
* Please make sure to bound check access to slices (for example: `value := strings[offset+1]`, maybe we have a incomplete list and value isn't present) that would otherwise result in a crash 

Please do open a PR so we can add this to the lib :)
