### ISSUE TITLE
Returning multiple values from the Agent

### ISSUE THREAD

**Issue by megarajan** [criteo/haproxy-spoe-go#7]
Is there any way to return multiple values from the Agent to HAProxy ?

For example, can I add more values to the following statement  ?

return []spoe.Action{
			spoe.ActionSetVar{
				Name:  "is_authenticated",
				Scope: spoe.VarScopeSession,
				Value: authenticated,
			},
		}, nil

**Comment by ShimmerGlass** [comment]
Yes, as you can see the return type is a slice, so you can do the following : 
```go
return []spoe.Action{
  spoe.ActionSetVar{
    Name: "is_authenticated",
    Scope: spoe.VarScopeSession,
    Value: authenticated,
  },
  spoe.ActionSetVar{
    Name: "my_other_var",
    Scope: spoe.VarScopeSession,
    Value: "hello spoe",
  },
}, nil
```

**Comment by megarajan** [comment]
thnx for the confirmation.
