### ISSUE TITLE
Question : SPOE: [auth-agents] failed to process messages: code=1

### ISSUE THREAD

**Issue by megarajan** [criteo/haproxy-spoe-go#8]
Hi

I see this error in my haproxy log whenever I do a CURL request.

Sep  3 03:29:46 172.17.0.8 haproxy[15289]: SPOE: [auth-agents] failed to process messages: code=1

I am not able to enable more debugs to figure out reason for this error.

Is there any way I can see more info on message transactions of this code and haproxy ?

thanks for the help.

**Comment by ShimmerGlass** [comment]
Hi, can you enable the debug flag in the global section and paste the output? Any output from your app ?

**Comment by megarajan** [comment]
increasing the timeouts somehow seem to have made the messages disappear. thanks for helping out.
